version: '3'

services:
  ca:
    image: ghcr.io/turboboulder/turboboulder/caimage:0.1
    networks:
      - dotnetapisqlbridge
    ports:
      - 8000:8000
    container_name: ca
    volumes:
      - ./ca/certs:/app/certs
    env_file:
      - ca/dev.env


  db:
    image: ghcr.io/turboboulder/turboboulder/idasqlserverexpress:0.1
    networks:
      - dotnetapisqlbridge
    ports:
      - 1433:1433
    volumes:
      - ./sqlserver/sql-data:/var/opt/mssql/data    
      - ./sqlserver/init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: db
    env_file:
      - sqlserver/dev.env
    

networks:
  dotnetapisqlbridge:
    external: true