version: '3'

services:
  ca:
    image: caimage:latest
    networks:
      - dotnetapisqlbridge
    ports:
      - 8000:8000
    container_name: ca
    volumes:
      - ./ca/certs:/app/certs
    env_file:
      - ca/dev.env


  db:
    image: idasqlserverexpress:0.1
    networks:
      - dotnetapisqlbridge
    ports:
      - 1433:1433
    hostname: testhost.idania.se
    volumes:
      - ./sqlserver/sql-data:/var/opt/mssql/data    
    container_name: db
    env_file:
      - sqlserver/dev.env
    

  # api:
  #   image:

  # frontendserver:
  #   image:


    

networks:
  dotnetapisqlbridge:
    external: true