name: Docker build and push

on:
  push:
    paths:
      - 'tools/docker/**'
  pull_request:
    paths:
      - 'tools/docker/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Build and push Docker CA image
      uses: docker/build-push-action@v2
      with:
        context: ./tools/docker/ca
        push: true
        tags: ghcr.io/${{ github.repository }}/caimage:0.1

    - name: Build and push Docker SQL Server image
      uses: docker/build-push-action@v2
      with:
        context: ./tools/docker/sqlserver
        push: true
        tags: ghcr.io/${{ github.repository }}/idasqlserverexpress:0.1
