name: Docker build and push

on:
  push:
    paths:
      - 'tools/docker/**'
  pull_request:
    paths:
      - 'tools/docker/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set repo name to lowercase
      id: repo-name-lowercase
      run: echo "::set-output name=repo::$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')"

    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: tools/docker/ca
        file: ./tools/docker/ca/Dockerfile
        push: true
        tags: ghcr.io/${{ steps.repo-name-lowercase.outputs.repo }}/caimage:0.1


    - name: Build and push Docker CA image
      uses: docker/build-push-action@v2
      with:
        context: ./tools/docker/ca
        push: true
        tags: ghcr.io/${{ steps.repo-name-lowercase.outputs.repo }}/caimage:0.1

    - name: Build and push Docker SQL Server image
      uses: docker/build-push-action@v2
      with:
        context: ./tools/docker/sqlserver
        push: true
        tags: ghcr.io/${{ steps.repo-name-lowercase.outputs.repo }}/idasqlserverexpress:0.1
