name: testflow

on:
  push:
    branches:
      - 0.01b
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Zip files
        run: |
          zip -r project_files_test.zip api frontend shared TurboBoulder.sln

      - name: "Get branch name and save to env"
        env:
          IS_PR: ${{ github.EVENT_NAME == 'pull_request' }}
        run: |
          if ${IS_PR}; then
            BRANCH_NAME="${GITHUB_HEAD_REF}"
          else
            BRANCH_NAME="${GITHUB_REF##*/}"
          fi
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "Release_${{ env.BRANCH_NAME }}_${{ github.run_number }}"
          release_name: "Release_${{ env.BRANCH_NAME }}_${{ github.run_number }}"
          body: Test only
          draft: false
          prerelease: true

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./project_files_test.zip
          asset_name: project_files_test.zip
          asset_content_type: application/zip

      - name: Create config file
        run: |
          echo "${{ steps.create_release.outputs.upload_url }}" > downloadurl.conf

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'  # adjust this according to your project's requirement

      - name: Build project - Windows
        run: |
          cd tools/cli
          dotnet publish -c Release -r win10-x64 --self-contained false
          cp ../../downloadurl.conf ./bin/Release/net7.0/win10-x64/publish/downloadurl.conf
          zip -r windows_asset.zip ./bin/Release/net7.0/win10-x64/publish
          cd ../..
        shell: bash

      - name: Create Windows Release
        id: create_windows_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "Windows_Release_${{ env.BRANCH_NAME }}_${{ github.run_number }}"
          release_name: "Windows_Release_${{ env.BRANCH_NAME }}_${{ github.run_number }}"
          body: Windows Test only
          draft: false
          prerelease: true

      - name: Upload Windows Release Asset
        id: upload-windows-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_windows_release.outputs.upload_url }}
          asset_path: ./tools/cli/windows_asset.zip
          asset_name: windows_asset.zip
          asset_content_type: application/zip

      - name: Build project - Linux
        run: |
          cd tools/cli
          dotnet publish -c Release -r linux-x64 --self-contained false
          cp ../../downloadurl.conf ./bin/Release/net7.0/linux-x64/publish/downloadurl.conf
          zip -r linux_asset.zip ./bin/Release/net7.0/linux-x64/publish
          cd ../..
        shell: bash

      - name: Create Linux Release
        id: create_linux_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "Linux_Release_${{ env.BRANCH_NAME }}_${{ github.run_number }}"
          release_name: "Linux_Release_${{ env.BRANCH_NAME }}_${{ github.run_number }}"
          body: Linux Test only
          draft: false
          prerelease: true

      - name: Upload Linux Release Asset
        id: upload-linux-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_linux_release.outputs.upload_url }}
          asset_path: ./tools/cli/linux_asset.zip
          asset_name: linux_asset.zip
          asset_content_type: application/zip
